apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    metadata:
      name: db-migrate
    spec:
      containers:
        - name: db-migrate
          image: tyh835/ruby-on-rails
          imagePullPolicy: Always
          command:
            - bin/rails
            - db:migrate
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-master-key
                  key: value
            - name: DATABASE_URL
              value: postgresql://postgres:yourpassword@postgres:5432/postgres?encoding=utf8&pool=20&timeout=5000
      restartPolicy: OnFailure
