default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password: yourpassword

development:
  <<: *default
  database: rails-on-ecs_development

test:
  <<: *default
  database: rails-on-ecs_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>