version: "3"

services:
  postgres:
    image: postgres:10.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: rails-app
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - RAILS_MAX_THREADS=5
      # NOTE: this key is for demo purposes. You should generate your own `master.key`
      - RAILS_MASTER_KEY=908df32fa781768497774479f839c789
      # uncomment these below to test out production env locally
      # - RAILS_ENV=production
      # - DATABASE_URL=postgresql://postgres:yourpassword@postgres:5432?encoding=utf8&pool=5&timeout=500

volumes:
  postgres:
